### ISSUE TITLE
Normalization of NaN is not working as intended

### ISSUE THREAD

**Issue by mrckzgl** [AI-team-UoA/pyJedAI#23]
The data class tries to normalize na / nan values into empty strings.
This is done here:
https://github.com/AI-team-UoA/pyJedAI/blob/a668c98487f8f1fcdff72fa9d82473449b279c80/src/pyjedai/datamodel.py#L126-L130
but it does not work as intended.
When casting the DataFrame to str, all nan values will be replaced with the string "nan" and fillna does nothing anymore.
see:
```
>>> pandas.DataFrame.isnull(pandas.DataFrame([numpy.nan]).astype(float))
      0
0  True
>>> pandas.DataFrame.isnull(pandas.DataFrame([numpy.nan]).astype(str))
       0
0  False
>>> 
```
Though, I do not know the best way to handle the intended conversion. One way could be to just change the order, first do fillna and later cast to string. But I don't know what happens if fillna('', inplace=True) is thrown against dtypes incompatible with / other than a string.

best

**Comment by Nikoletos-K** [comment]
Hello, and I'm sorry for the late reply.

Yeah you're right on your remarks. Indeed NaN handling has no effect this way. So changing rows I think do the trick.

```
        # Fill NaN values with empty string
        self.dataset_1.fillna("", inplace=True)
        self.dataset_1 = self.dataset_1.astype(str)
        if not self.is_dirty_er:
            self.dataset_2.fillna("", inplace=True)
            self.dataset_2 = self.dataset_2.astype(str)
```

As far as the str transformation, it is necessary in order to assure that no other types will be handled. It caused issues in many  other steps, and that's why we decided to handle it this way. 

The above fix will be uploaded in the next release.

Thank you that you shared it with us!

Konstantinos
